# Generated by Django 5.0.6 on 2026-01-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short user biography (max 240 chars)', max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text="User's display name (e.g. 'John Doe')", max_length=100, null=True),
        ),
    ]
