# Generated by Django 5.0.6 on 2026-01-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_userprofile_bio_userprofile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_private',
            field=models.BooleanField(default=False, help_text="If true, only approved followers can see this profile's content"),
        ),
    ]
